### ISSUE TITLE
Event Parameters aren't saved unless prefab is applied

### ISSUE THREAD

**Issue by async0x42** [Thundernerd/Unity3D-ExtendedEvent#3]
If you change the parameters on a method, without applying the prefab changes, it reverts to the preview saved data.

![game](https://cloud.githubusercontent.com/assets/3268854/12375658/e3542faa-bc9a-11e5-8c7c-92c865ea0bc5.gif)

**Comment by Thundernerd** [comment]
Thanks for the report. Just tested it out myself and it seems there are indeed some issues regarding prefabs. I'll take a look at it and see what I can do to fix it.

**Comment by Thundernerd** [comment]
I've created a fix for this (d9406e2, d11d011) though in my opinion it's not so elegant.

I've added a button in the header of the event list with the text "Apply" that only appears on prefab instances. The reason I use a button for this is because as soon as you click it will update a lot of references (blame Unity) which takes time, so I cannot do it the moment after the change has been made since it would feel terribly slow.

Here's an example of what it will look like before and after you click the button.
![Before](http://i.imgur.com/Z4tklmg.png)
![After](http://i.imgur.com/pH4y8LJ.png)

I will add it to the next release which should be up soon.

If you have any further questions/issues feel free to open a new issue.
